name: Deployment MultiApi

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          path: MultiApi
      - name: List files for debugging
        run: ls -la
        working-directory: MultiApi
      - uses: actions/setup-node@v4
        with:
          node-version: 16.6.0
      - run: npm install
        working-directory: MultiApi
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          path: MultiApi
      - name: Install Railway
        run: npm i -g @railway/cli
        working-directory: MultiApi
      - name: List files for debugging before deploy
        run: ls -la
        working-directory: MultiApi
      - name: Deploy with Railway
        run: railway up --service MultiApi
        working-directory: MultiApi
        env:
          RAILWAY_TOKEN: ${{ secrets.APIS}}